services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Npostnik\BePermissions\:
    resource: '../Classes/*'

  Npostnik\BePermissions\Command\ExportBegroupsCommand:
    tags:
      - name: 'console.command'
        command: 'begroups:export'
        description: 'Export BE groups in yaml files'

  Npostnik\BePermissions\Command\ImportBegroupsCommand:
    tags:
      - name: 'console.command'
        command: 'begroups:import'
        description: 'Import BE groups from yaml files'
